import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.testarchitect.com/product-category/electronic-components-supplies/?view_mode=list');
  await page.getByRole('link', { name: 'DJI Mavic Pro Camera Drone', exact: true }).click();
  await page.getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('link', { name: '1 $' }).click();
  await page.getByRole('link', { name: 'DJI Mavic Pro Camera Drone' }).click();
  await page.goto('https://demo.testarchitect.com/cart/');
  await page.getByRole('row', { name: 'DJI Mavic Pro Camera Drone' }).locator('bdi').nth(1).click();
  await page.getByRole('spinbutton', { name: 'DJI Mavic Pro Camera Drone' }).click();
  await page.getByRole('row', { name: 'DJI Mavic Pro Camera Drone' }).locator('bdi').nth(2).click();
  await page.getByRole('row', { name: 'Subtotal $' }).locator('bdi').click();
  await page.getByRole('row', { name: 'Total $129.00', exact: true }).locator('bdi').click();
  await page.getByRole('link', { name: 'Proceed to checkout' }).click();
  await page.getByRole('cell', { name: 'DJI Mavic Pro Camera Drone  ×' }).click();
  await page.getByRole('row', { name: 'DJI Mavic Pro Camera Drone' }).locator('bdi').click();
  await page.getByRole('row', { name: 'Subtotal $' }).locator('bdi').click();
  await page.getByRole('row', { name: 'Total $129.00', exact: true }).locator('bdi').click();
  await page.getByRole('textbox', { name: 'First name *' }).click();
  await page.getByRole('textbox', { name: 'First name *' }).fill('Tam');
  await page.getByRole('textbox', { name: 'First name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last name *' }).fill('Phan');
  await page.getByRole('textbox', { name: 'Company name (optional)' }).click();
  await page.getByRole('textbox', { name: 'Company name (optional)' }).fill('LogiGear');
  await page.getByRole('textbox', { name: 'Street address *' }).click();
  await page.getByRole('textbox', { name: 'Street address *' }).fill('1234 Main St');
  await page.getByRole('textbox', { name: 'Town / City *' }).click();
  await page.getByRole('textbox', { name: 'Town / City *' }).fill('Houston');
  await page.getByRole('textbox', { name: 'California' }).click();
  await page.getByRole('combobox').filter({ hasText: /^$/ }).fill('texa');
  await page.getByRole('option', { name: 'Texas' }).click();
  await page.getByRole('textbox', { name: 'ZIP Code *' }).click();
  await page.getByRole('textbox', { name: 'ZIP Code *' }).click();
  await page.getByRole('textbox', { name: 'ZIP Code *' }).fill('77077');
  await page.getByRole('textbox', { name: 'Phone *' }).click();
  await page.getByRole('textbox', { name: 'Phone *' }).fill('0123456789');
  await page.getByRole('textbox', { name: 'Email address *' }).click();
  await page.getByRole('textbox', { name: 'Email address *' }).fill('tamp@logiear.com');
  await page.getByRole('textbox', { name: 'Order notes (optional)' }).click();
  await page.getByRole('textbox', { name: 'Order notes (optional)' }).fill('testing');
  await page.getByRole('button', { name: 'Place order' }).click();
  await page.goto('https://demo.testarchitect.com/checkout/order-received/14477/?key=wc_order_6w9Qg3itiZzPe');
  await page.getByText('Thank you. Your order has').click();
  await page.getByText('Order number: 14477 Date:').click();
  await page.getByText('Order number: 14477 Date:').click();
  await page.getByRole('link', { name: 'Order status' }).click();
});